spring:
  application:
    name: exposer
  main:
    banner-mode: OFF

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
        - health

logging:
  level:
    root: OFF
    com.glinboy.exposer: INFO

springdoc:
  swagger-ui:
    docExpansion: none

application:
  info:
    description: Expose applivation env and system variables
    version: 0.0.1-SNAPSHOT
    license: MIT license
    license-url: https://github.com/GLinBoy/system_info_exposer/blob/main/LICENSE.md
    github-url: https://github.com/GLinBoy/system_info_exposer